# Generated by Django 5.2.3 on 2025-07-15 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_eventschedule_feedback_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 15, 23, 46, 6, 471302)),
            preserve_default=False,
        ),
    ]
