# Generated by Django 5.2.3 on 2025-08-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feedback_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actual_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_engagement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_success_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
