# Generated by Django 5.2.3 on 2025-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_actual_attendees_event_actual_engagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actual_sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
